### PR TITLE
Incorporated all changes that were made in SBA V1.5.3 for ZC 1.5.1.

### PR DESCRIPTION
**Pull request by mc12345678**
This did include revision of determining previously ordered products that
have attributes and are tracked by SBA.
Wanted to get some of the testing started.  Still have some delete variant(s) based on other actions to do in attributes_controller; however, need to know if have missed anything in the rest of the code.

### CODE REVIEW

**Comment by jeking928** [comment]
I installed this branch on a stock 1.5.3 Zen Cart. After adding mixed attrbiutes for a product, all attributes disappear on the product page.
image

**Comment by mc12345678** [comment]
Try removing the templated tpl_modules_attributes.php file, does that resolve the issue?

If so, then need to add an additional check in that file because I forgot dynamic dropdowns defines TABLE_PRODUCTS_STOCK to point at the same table already defined and used by SBA (TABLE_PRODUCTS_WITH_STOCK_ATTRIBUTES) and so perhaps that is being referenced in the template which if not installed causes a "loss" of the attributes.

Chad M.
-----Original Message-----

**Comment by jeking928** [comment]
Removing templated tpl_modules_attributes.php did fix the problem.  When you have a chance to post the fixed file, I'll check again.

Jim

**Comment by mc12345678** [comment]
My guess is that you also have an error log associated with that. If you wouldn't mind double checking. Probably something about the table not existing...

Chad 
-----Original Message-----

**Comment by jeking928** [comment]
Actually, no error log at all.

Jim

mc12345678 wrote:

**Comment by mc12345678** [comment]
Corrected issue with tpl_modules_attributes.php for installation on new ZC without Dynamic Dropdowns installed...

**Comment by jeking928** [comment]
Confirmed this issue is fixed.

**Comment by jeking928** [comment]
Two new issues, the displayed qty is incorrect and the displayed options are incorrect. With a stock 1.5.3, I have stock set as:
image
Stock is displayed as:
image

There is only 20 of the 'Value' in stock.  35 is the total of all attributes.
The Memory option has all six values instead of just the three actual memory values.

The issue, I believe, is the added complexity of mixed attributes.  I realize some have a need for this but I'm not sure the added complexity is worth it. I think mixed attributes are better handled by setting a single attribute and more values. For this product, it would be one option name with six values.  This scenario is easily handled by SBA and simplifies the display and selection for the shopper.

**Comment by mc12345678** [comment]
If I am not mistaken, I have not modified the attributes.php file.  In fact I have avoided work on it, because of previous changes that were made to support a different issue (several months ago). One such change caused product to appear multiple times in a single dropdown, typically in the first or earlier dropdowns.

One of the longstanding downfalls to SBA has been exactly that it does not/has not properly handled mixed attributes.  It is not a "some people" concern/issue.  I will say that so far the code provided here has been able to work with Dynamic Dropdowns to at least provide indication of product that is out-of-stock; however, I would agree that the attributes.php file has some aspects requiring work... Noticed in merge/comparison yesterday with ZC 1.5.3 includes/modules/attributes.php that there are a number of pricing adjustment actions that are not considered.

Reducing the number of store attributes to accommodate SBA would be counter-intuitive to the flexibility and functionality of ZC, where attributes can be copied and mixed with various product.  Moving to this path would increase the number of single entries to the number of combinations available by mixing and matching attributes instead of using the database scheme to present/modify the display data.

If instead, SBA were to combine multiple/mixed attributes into a single dropdown option, then that may be solvable without further need of java to update other fields (price, quantity available, other options available) on the fly.  However, that said, the list presented to the customer when there are 3, 4 or more attributes would be tremendous... If each had 4 options, then instead of 4 individual option names, a product with 3 attributes would have 64 selections, a product with 4 attributes would have 256 options to select.... I believe that this gross quantity of options would be unacceptable to any store owner.

So, I know that I was asked also if Dynamic Dropdowns would be incorporated into this plugin.  I think that the answer should be no, as not everyone would need the multi-attribute functionality that it supports; however, as evidence from including the modified tpl_module_attributes.php file, action can be taken to consider that plugin from being used...

Tracking the quantity available adjacent to the individual listing, does require java updating of the value(s) upon selection, which also has not addressed, ensuring core capability and functionality is present with follow-on results to come.  If the product works as is with single attributes without fault, then the multiple-attribute functionality currently in place should be considered for the remaining development.  In all cases of adding functionality, the attempt has been made to not affect what already works, but to build on the operation, even though there are some base actions carried over from previous SBA variants that do not have clear explanation of why that action was taken.

**Comment by jeking928** [comment]
I guess I'm not sure how to proceed.  I'll concede that a value list can easily get to be too long to be manageable.  But the current display creates issues that cause confusion. See here: http://bit.ly/1sHHv4R

The drop-downs do not reflect the actual quantities or stock values.

**Comment by mc12345678** [comment]
Let me ask this... Does the same problem occur with the main thread of the software?  If not what is the difference that is causing the result.  If it does, then I say that the code to generate/determine the quantity available needs to be modified.  Yes, it is confusing to have so many different options on display.  In the test environments I have used, they typically show in the first attribute not the second, but it is confusing and personally I thought it was something previously known to be worked out, so didn't want to touch it if there was parallel work. This is also what was basically being reported in #21 although there was more going on there as well...

I guess, it appears that as the individual reporting issue #21 was using the main thread, that the issue exists throughout not just in this line of code.  There are improvements in this code that I believe will help in all cases and recommend incorporating this code into the main thread and then correcting the multiple attribute issue(s) of the main thread... It is either in the code leading up to displaying the javascript, or some form of "calculation" performed in the javascript... I have looked at neither and was just starting to look at what generates the multiple option name selections and why only one of the two (haven't tried a three attribute product) attributes is so confusing by providing multiple selections for each attribute type.

**Comment by jeking928** [comment]
I knew you'd ask 'Does the same problem occur with the main thread of the software?' and I was going to check.  It turns out it does so it does seem to be related to #21 so I'll move comments to that thread.

**Pull request merged**
